### ISSUE TITLE
Ajuda por favor :/

### ISSUE THREAD

**Issue by leonardofmed** [giorgiofellipe/cordova-plugin-datecsprinter-example#13]
Não entendi muito bem como funciona o exemplo, preciso estar com o cordova-plugin-datecs-printer previamente instalado?
Só preciso substituir os arquivos da sua pasta para a pasta do meu app?

**Comment by giorgiofellipe** [comment]
Basta clonar o repositório, rodar `npm install` e então rodar em um dispositivo Android.
