### ISSUE TITLE
Auto cut function

### ISSUE THREAD

**Issue by rodolfofelipeov** [giorgiofellipe/cordova-plugin-datecsprinter-example#14]
Olá, 
Utilizo seu plugin, funciona super bem. 
Preciso apenas de uma função para realizar o corte automático quando imprime, seria possível desenvolvê-la? 
Por questões de produtividade, me seria extremamente útil esta função.
Desde já, muito obrigado. 
Fico no Aguardo.

**Comment by giorgiofellipe** [comment]
Nem todas as impressoras respondem ao mesmo comando de acionamento da guilhotina. As impressoras Urano, por exemplo, respondem à este `1B69`.

Implemente em seu serviço de impressão o seguinte comando após as impressões:

```javascript
        window.DatecsPrinter.writeHex('1B69',
          function (success) {

          },
          function (error) {

          }
        );
```

**Comment by rodolfofelipeov** [comment]
Muito obrigado!
Funcionou perfeitamente.

Uma outra dúvida...

É possível controlar a velocidade de impressão?
Pergunto porque estou achando a velocidade de impressão um pouco lenta.
Peço desculpas se a pergunta que estou fazendo não tiver nenhum tipo de relação com o plugin que desenvolveu.

Agradeço desde já.

**Comment by giorgiofellipe** [comment]
Fico feliz que funcionou.
A velocidade de impressão é configuração da impressora.
