### ISSUE TITLE
Error DatecsPrinter is not defined

### ISSUE THREAD

**Issue by lucav90** [giorgiofellipe/cordova-plugin-datecsprinter-example#2]
Hi,

i have this problem. 

DatecsPrinter is not defined

How can i solve?

Regards,

**Comment by giorgiofellipe** [comment]
@lucav90 As well as any other plugin it will only be available after `deviceready` event is fired, be sure you're trying to use it after this

**Comment by lucav90** [comment]
Hi,

i use ionic e angular. I have:
-  the datecsprinter.service.js in my index.html
- in the controller.js -> angular.module('app.controllers', ['ngCordova','app.service.datecsprinter', 

i have this function but doens't work. 
The error is ReferenceError: DatecsPrinter is not defined:

$scope.scanprinter = function(){

	$ionicPlatform.ready(function() {
		alert('inside printer');
		
      DatecsPrinter.listBluetoothDevices()
        .then(function (addresses) {
          return DatecsPrinter.connect(addresses[0]);
        })
        .then(function (success) {
          return DatecsPrinter.printText("Printing test!{br}");
        })
        .then(function (success) {
          return DatecsPrinter.feedPaper(100);
        })
        .then(function (success) {
          return DatecsPrinter.disconnect();
        })
        .catch(function (error) {
          alert("Error!");
        });
		
	})

}

**Comment by giorgiofellipe** [comment]
`DatecsPrinter` is a angular service that you can find [here](https://github.com/giorgiofellipe/cordova-plugin-datecsprinter-example/blob/master/www/js/datecsprinter.service.js) and it should be injected as dependency as is done [here](https://github.com/giorgiofellipe/cordova-plugin-datecsprinter-example/blob/master/www/js/controllers.js#L44)

**Comment by lucav90** [comment]
Hi, thansk.

I have this another error: 

`TypeError: Cannot read property 'listBluetoothDevices' of undefined at file:///android_asset/www/js/printer/datecsprinter.service.js:17:30`

**Comment by lucav90** [comment]
Hi,

what is the correct procedure to print some text with bluethooh printer with your source code? 
I have more problems and error with your code.

Please tell us the solution to solve

**Comment by giorgiofellipe** [comment]
It is working as it is, clone the repository again and follow the recent added instructions on README
