### ISSUE TITLE
Print special html tag with an image

### ISSUE THREAD

**Issue by lucav90** [giorgiofellipe/cordova-plugin-datecsprinter-example#3]
Hi,

i have read your specific functions like: DatecsPrinter.printBarcode, DatecsPrinter.printMyImage but how can i print same html page like 
ex: `<table witdh='500'><tr><td width='250'><img src=""></td><td `width='250'></td></tr></table>` ?

I want to implement this simple page or other html tag and print it.

**Comment by giorgiofellipe** [comment]
It's not possible to print html tags. Read the [plugin README](https://github.com/giorgiofellipe/cordova-plugin-datecs-printer#cordova-plugin-datecs-printer) carefully and you'll find your answers.
