### ISSUE TITLE
Cannot print on example app

### ISSUE THREAD

**Issue by matheusgs05** [giorgiofellipe/cordova-plugin-datecsprinter-example#4]
I am trying to run the example app, but when i click on "Print Test", i get the message on chromium logcat:

TypeError: Cannot read property 'listBluetoothDevices' of undefined

I downloaded the project, run npm install and run the app. Can you help me please?

**Comment by matheusgs05** [comment]
I also tryed to install the plugin on some HelloWorld app of mine.

I get the following error:

12-12 20:26:22.724 13300 13300 I chromium: [INFO:CONSOLE(312)] "Error in Error callbackId: DatecsPrinter1358990610 : ReferenceError: error is not defined", source: file:///android_asset/www/cordova.js (312)
12-12 20:26:22.724 13300 13300 I chromium: [INFO:CONSOLE(314)] "Uncaught ReferenceError: error is not defined", source: file:///android_asset/www/cordova.js (314)

Can someone help me please?

**Comment by giorgiofellipe** [comment]
- Be sure that the plugin is installed: `cordova plugin add cordova-plugin-datecs-printer`
- As well as any other plugin it will only be available after deviceready event is fired, be sure you're trying to use it after this
- It will only work on devices
- `DatecsPrinter` is a angular service that you can find [here](https://github.com/giorgiofellipe/cordova-plugin-datecsprinter-example/blob/master/www/js/datecsprinter.service.js) and it should be injected as dependency as is done [here](https://github.com/giorgiofellipe/cordova-plugin-datecsprinter-example/blob/master/www/js/controllers.js#L44)
- Read carefully the plugin [README](https://github.com/giorgiofellipe/cordova-plugin-datecs-printer#cordova-plugin-datecs-printer)

**Comment by athuu** [comment]
Hi Giorgiofellipe 

Thank you so much for a great plugin. 

1).Hhaving some doubts regards the tags. how can i print with html tags like <h1> <table> <td> <ul> tags in Datacs-printer.
2). The dialog box appear at the time printings is checking the printer if its not found its will not closed for timeout. its continously searching for long time.
3). if i change the charset UTF-8 it will change the encode?
4). How can i use all Html tags and how i set the size 

Thanks in advanced

**Comment by giorgiofellipe** [comment]
@athuu 
`1` & `4` it's not possible to print using html tags atm.
`3` You can set the charset by passing it to `printText` method as you can see [here](https://github.com/giorgiofellipe/cordova-plugin-datecsprinter-example/blob/master/www/js/datecsprinter.service.js#L83)
